kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: flapp-operator-leader
subjects:
  - kind: ServiceAccount
    name: flapp-operator
    namespace: leader
roleRef:
  kind: ClusterRole
  name: flapp-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: flapp-operator-follower
subjects:
  - kind: ServiceAccount
    name: flapp-operator
    namespace: follower
roleRef:
  kind: ClusterRole
  name: flapp-operator
  apiGroup: rbac.authorization.k8s.io
